networks:
  docker:
    name: docker
    external: true

services:
  caddy:
    image: 'caddy:latest'
    container_name: caddy
    hostname: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
      - 2019:2019
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./logs:/var/log/caddy
      - ./srv:/srv
      - ./data:/data
      - ./config:/config
    environment:
      - TZ=Asia/Seoul
    networks:
      - docker
    # labels:
    #   - com.centurylinklabs.watchtower.enable=true
