networks:
  docker:
    name: docker
    external: true

volumes:
  grafana_data:
    name: grafana_data
  grafana_prometheus_data:
    name: grafana_prometheus_data

services:
  grafana-loki:
    image: 'grafana/loki:latest'
    container_name: grafana-loki
    hostname: grafana-loki
    restart: unless-stopped
    command:
      - -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100:3100
    environment:
      - TZ=Asia/Seoul
    networks:
      - docker

  grafana-alloy:
    image: 'grafana/alloy:latest'
    container_name: grafana-alloy
    hostname: grafana-alloy
    restart: unless-stopped
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    ports:
      - 12345:12345
    volumes:
      - ./config/alloy:/etc/alloy
      - ../caddy/logs:/var/log
    environment:
      - TZ=Asia/Seoul
    networks:
      - docker
    depends_on:
      - grafana-loki

  grafana-prometheus:
    image: 'prom/prometheus:latest'
    container_name: grafana-prometheus
    hostname: grafana-prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus:/etc/prometheus
      - grafana_prometheus_data:/prometheus
    environment:
      - TZ=Asia/Seoul
    networks:
      - docker

  grafana:
    image: 'grafana/grafana:latest'
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    command:
      - --config=/etc/grafana-config/grafana.ini
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana:/etc/grafana-config
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      - TZ=Asia/Seoul
    networks:
      - docker
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/healthz']
      interval: 1s
      timeout: 10s
      retries: 5
